name: 'Verify packaging'
description: 'verify package import'

runs:
  using: 'composite'
  steps:
    - name: Setup environment
      uses: quintenroets/actions/setup/environment@main
      with:
        extra-dependency: package-dev-tools

    # Cached environment can contain previous commit
    - name: Install current commit
      shell: bash
      run: pip install .

    - name: Verify package
      shell: bash
      run: |
        package_name=$(extract-package-name)
        python -c "import $package_name"
