name: Instantiate new project
description: 'Instantiate new project from template repository'

runs:
  using: 'composite'
  steps:
  - name: Checkout source
    uses: actions/checkout@v3

  - name: Install dependencies
    uses: quintenroets/actions/setup/environment@main
    with:
      dependency: package-dev-tools

  - name: Run instantiation
    run: instantiate-new-project --project-name ${{ github.event.repository.name }}
    shell: bash

  - name: Push changes
    run: git push
    shell: bash
