name: Publish project
description: Publish project on PyPI

runs:
  using: composite
  steps:
    - name: Install dependencies
      uses: quintenroets/actions/setup/environment@main
      with:
        dependency: build

    - name: Build
      run: uv build
      shell: bash

    - name: Upload distribution to PyPI
      run: uv publish
      shell: bash
