name: 'Extract Python versions'
description: 'Extract Python versions supported by the project'

outputs:
  versions:
    description: "The Python versions supported by the project"
    value: ${{ steps.extract-python-versions.outputs.versions }}

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        clean: false
        show-progress: false

    - name: Setup environment
      uses: quintenroets/actions/setup/environment@main
      with:
        dependency: package-dev-tools

    - name: Extract Python version
      id: extract-python-versions
      shell: bash
      run: echo "versions=$(extract-supported-python-versions)" >> "$GITHUB_OUTPUT"
