name: Publish project
description: Publish npm project on GitHub

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        clean: false
        show-progress: false

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm install

    - name: Build
      shell: bash
      run: npm run build

    - name: Publish on Github
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        dist="dist.zip"
        version=$(jq -r ".version" package.json)
        cd dist
        zip -rq $dist .
        if gh release list | grep v0.1.0 then; then
            gh release delete-asset -y v$version $dist
        else
            gh release create v$version --generate-notes
        fi
        gh release upload v$version $dist#"Distribution (zip)"
