name: Setup npm project

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        clean: false
        show-progress: false

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        cache: npm
