name: Setup bun project

runs:
  using: composite
  steps:
    - uses: actions/checkout@v5
      with:
        clean: false
        show-progress: false

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
