name: 'Sync template'
description: 'Sync changes from the template repository'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      uses: quintenroets/actions/setup/environment@main
      with:
        dependency: package-dev-tools

    - name: Sync template
      run: sync-template --token ${{ github.token }}
      shell: bash
