name: 'Sync template'
description: 'Sync changes from the template repository'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      uses: quintenroets/actions/setup/environment@main
      with:
        dependency: "package-dev-tools >=0.5.8, <1"

    - name: Sync template
      run: sync-template --token ${{ github.token }} --repository ${{ github.repository }}
      shell: bash
