name: 'Run pre-commit hooks'
description: 'Run pre-commit hooks'

runs:
  using: 'composite'
  steps:
    - name: Setup environment
      uses: quintenroets/actions/setup/environment@main
      with:
        environment: dev
        editable: true

    - name: Cache mypy
      id: cache
      uses: actions/cache@v4
      env:
        KEY:
          mypy
          ${{ runner.os }}
          ${{ steps.determine-python-version.outputs.python_version }}
      with:
        save-always: true
        path: |
          .mypy_cache
        key: ${{ env.KEY }}
        restore-keys: ${{ env.KEY }}

    - name: Run hooks
      shell: bash
      run: make pre-commit
