name: Run tests

on:
  push:
  workflow_dispatch:

jobs:
  test-setup:
    name: Test setup
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: quintenroets/actions/setup/environment/@main
        with:
          dependency: superpathlib

  test-mount:
    name: Test mount
    runs-on: ubuntu-latest
    steps:
      - name: Mount
        uses: quintenroets/actions/mount-remote/@main
        with:
          rclone-secret: ${{ secrets.RCLONE }}

      - name: Verify access
        run: ls /media/backup | grep -q etc

  test-instantiate:
    name: Test instantiate
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: quintenroets/actions/setup/environment@main
        with:
          dependency: package-dev-tools

      - name: Checkout template repository
        uses: actions/checkout@v3
        with:
          repository: quintenroets/python-package-template
          path: python-package-template

      - name: Run instantiation
        run: instantiate-new-project --project-name test-package --path python-package-template

      - name: Visualize content
        run: tree python-package-template

      - name: Verify content
        run: tree python-package-template | grep test_package

  test-traceback-hooks:
    name: Test traceback hooks
    runs-on: ubuntu-latest
    steps:
      - name: Test traceback hooks
        uses: quintenroets/actions/setup/environment/@powertrace
        with:
          dependency: superpathlib

      - name: Debug
        run: |
          python -c "raise Exception" || :
