name: Build

on:
  push:

jobs:
  test-mount:
    name: Test mount
    runs-on: ubuntu-latest
    steps:
      - name: Test mount
        uses: quintenroets/actions/mount-remote/@main
        with:
          rclone-secret: ${{ secrets.RCLONE }}

      - name: Test access
        run: ls /media/backup | grep -q etc

  test-setup:
    name: Test setup
    runs-on: ubuntu-latest
    steps:
      - name: Test setup
        uses: quintenroets/actions/setup/environment/@main
        with:
          dependency: superpathlib
